### ISSUE TITLE
"Line number" colors

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.ThemeCustomizer#8] opened 2020-04-25 16:16 UTC
I can't work out where in the customizer I change the colour for the left hand column line numbers.

I checked with Inspect Element and could not see.

**Comment by ajtruckle** [comment] 2020-04-26 15:30
So I have need trying your latest beta and I see you have new features for the line numbers. :)

Look [here](https://www.publictalksoftware.co.uk/2020/04/25/meeting-schedule-assistant-version-20-1-4-newsletter/).

![Lines](https://user-images.githubusercontent.com/7985331/80312027-e1d9f780-87da-11ea-88e3-446e5fd5639e.png)

It looks really great - thanks! The only thing I noticed. Take for example, the way:

![Old](https://user-images.githubusercontent.com/7985331/80312058-15b51d00-87db-11ea-9361-63d60296c017.png)

It would be great if the new "line number" controls obeyed the highlight / hover highlight colours. This way the focus line number will stand out a little better. See?

**Comment by AndiDittrich** [comment] 2020-04-26 15:38
you should really take the time to create a full custom theme - the customizer is not designed to provide a 100% customization - it should be used as a starting point for own themes.

the problem is, that there are a lot of possible css classes which can be changed and it is nearly impossible to cover 100% of all settings

**Comment by ajtruckle** [comment] 2020-04-26 16:14
I understand you. But here is the thing - I like this theme 99%. So i don't want to have to re-construct a whole theme for the 1% which your customiser has catered for fantastically. :)

I do understand where you are coming from!

**Comment by AndiDittrich** [comment] 2020-04-26 16:14
you just have to copy+past the css and add some rules manually...it's very simple...

**Comment by ajtruckle** [comment] 2020-04-26 16:16
OK - maybe I will take the plunge. Sounds scary! Do you have a doc covering the basics of what to do or something about doing this?

**Comment by AndiDittrich** [comment] 2020-04-26 16:17
no...just learn css...

**Comment by ajtruckle** [comment] 2020-04-26 16:19
Where is the CSS file stored?

**Comment by AndiDittrich** [comment] 2020-04-26 16:20
don't edit this file. use an external theme with the content from the theme customizer

**Comment by ajtruckle** [comment] 2020-04-26 16:21
Yes, I am using a chime theme for my wordpress website. So whatever I do needs to go in there I guess.

**Comment by ajtruckle** [comment] 2020-04-26 16:25
> don't edit this file. use an external theme with the content from the theme customizer

What I meant was - how do I locate the original CSS file that I need to copy and customize? And where do I put my modified one? Sorry is you are having to teach me to suck eggs. :)

**Comment by AndiDittrich** [comment] 2020-04-26 16:26
open the contextual help on the enlighter settings page -> External Themes

the original css file keeps untouched. you're only adding an ADDITIONAL css file which contains the contents of the customizer

**Comment by ajtruckle** [comment] 2020-04-26 16:38
Ok, so I got to create a `enlighter` folder inside my child theme directory. But where do we go from there? Do I use inspecter to examine the existing elements to confirm what name I should give this CSS file? I did not see that in the contextual help.

BTW: "buildin" -> "built in" or "built-in". :)

**Comment by AndiDittrich** [comment] 2020-04-26 16:41
1. name it `myspecialtheme.css` or something like this - it is important that the filename (without the css extension is used as theme identifiert).

2. copy the content of the theme customizer (CSS tab) into this file

3. run search-replace in this file and replace `-t-wpcustom` with `-t-myspecialtheme`

4. enable external themes in `Enlighter -> Options -> Resources -> External Themes`

that should work and a new theme with the name "myspecialtheme" should appear in the theme list

**Comment by ajtruckle** [comment] 2020-04-26 16:56
Thanks. I am going to put this on hold. I certainly got a theme showing in the list (thank you for the instructions. But when I tried it it reverted to a very basic content. I was anticipating it would be based on m the current settings (customize theme) that i was using.

I had used the "Stylesheet" tab in the customizer. I figured that was the "CSS" tab you meant. But I had not anticipated having to perform a full theme customization from scratch.

Thanks all the same!

**Comment by AndiDittrich** [comment] 2020-04-27 09:09
i've added some kind of documentation about external-themes: https://github.com/EnlighterJS/documentation/blob/master/wordpress/ExternalThemes.md

additionally the master branch contains a minor change (css dependency issue) which may cause overlapping styles

**Comment by ajtruckle** [comment] 2020-04-27 09:22
Thanks. My pc is at the shops for repairs. CPU fan error.

Will check in due course.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment] 2020-04-27 14:33
I have my PC back. I thought I would try again in my staging area. My mistake was I had used capital letters in the file name and all lowercase in the class names. Since your themes have capital letters I had tried the same.

Making them all lowercase made it work again when I chose my theme. But there was an odd issue with your hover buttons:

![BUTTONS](https://user-images.githubusercontent.com/7985331/80384116-650f5200-889c-11ea-9311-9bb0610194f9.png)

**Comment by ajtruckle** [comment] 2020-04-27 16:30
Also, what I don''t get is that i can't see the line numbers in the inspector:
![Lines](https://user-images.githubusercontent.com/7985331/80396625-cb03d580-88ac-11ea-89ba-f74d2b5a3b9d.png)

Where are they in the code?

**Comment by AndiDittrich** [comment] 2020-04-28 08:11
css pseudo (virtual) elements are used for the numbering scheme: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements

the button issue should be fixed in the master branch (overlapping css styles)

**Comment by ajtruckle** [comment] 2020-04-28 08:55
> the button issue should be fixed in the master branch (overlapping css styles)

Thanks. I have updated my EnlighterJS and tried again on my staging site and now the buttons are OK. I think maybe my mistake was that I did not re-create the custom theme from scratch via your plugin tab. So the buttons are all good now.

> css pseudo (virtual) elements are used for the numbering scheme

Thanks for the link. I am getting there:

```
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::before{
	padding: 1px 5px 1px 14px;
	font-size: 1.3em;
	color: black;
	background-color: whitesmoke;
	border-right:thin black solid;
}
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special::before{
	background-color: #2F4F4F;
}

```
How do I isolate the "hover" `::before` pseudo element?

**Comment by AndiDittrich** [comment] 2020-04-28 09:12
`:hover::after` - but which color/behaviour do you want to change ?

**Comment by ajtruckle** [comment] 2020-04-28 09:15
Focused Highlighted Row

**Comment by AndiDittrich** [comment] 2020-04-28 09:15
`.enlighter-t-trucklesoft div.enlighter>div.enlighter-special:hover::before` may work

**Comment by ajtruckle** [comment] 2020-04-28 10:12
Thanks. I got that to work. It leaves one issue:

```
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::before{
	padding: 1px 5px 1px 14px;
	font-size: 1.3em;
	color: black;
	background-color: whitesmoke;
	border-right:thin black solid;
}
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::hover::before{
	background-color: #53616f;
}
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special::before{
	background-color: #2F4F4F;
}
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special:hover::before{
	background-color: #53616f;
}
.enlighter-t-trucklesoft.enlighter-hover div.enlighter>div:hover{
	background-color: #53616f;
}

```
I was trying `.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::hover::before` to set the colour for standard focused rows. Doesn't work.

**Comment by ajtruckle** [comment] 2020-04-28 10:21
Here is a zipped video.

[EnlighterJS-Video.zip](https://github.com/EnlighterJS/Plugin.ThemeCustomizer/files/4544997/EnlighterJS-Video.zip)

**Comment by AndiDittrich** [comment] 2020-04-28 10:43
it's a difference to use double and single colons

the pseudo elements are only used for the linenumbers. the outer div is used for the line background color

**Comment by ajtruckle** [comment] 2020-04-28 11:03
We are talking about the line number background still, I have tried a lot of things, like:
```
.enlighter-t-trucklesoft div.enlighter>div:hover:before{
	background-color: #53616f;
}
```
We have these scenarios:

- A **normal** line of code (we have `whitesmoke` as the background for the line numbers):

![line1](https://user-images.githubusercontent.com/7985331/80479745-68134c80-8947-11ea-856e-f5883a3e067b.png)

```
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::before{
	background-color: whitesmoke;
}
```
- A **highlighted** line of code (we have `#2F4F4F` as the background for the line numbers):

![Line2](https://user-images.githubusercontent.com/7985331/80479816-87aa7500-8947-11ea-9df3-207378d48f85.png)

```
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special::before{
	background-color: #2F4F4F;
}
```
- A **focused highlighted** line of code  (we have `#53616f` as the background for the line numbers):

![Line3](https://user-images.githubusercontent.com/7985331/80479884-a3ae1680-8947-11ea-8a62-38c43c6a6e54.png)


```
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special:hover::before{
	background-color: #53616f;
}
```
- A **focused normal** line of code (we want to have `#53616f` as the background for the line numbers).

![Line4](https://user-images.githubusercontent.com/7985331/80479946-bd4f5e00-8947-11ea-90a6-e4afb394b3d7.png)

> it's a difference to use double and single colons
> 
> the pseudo elements are only used for the linenumbers. the outer div is used for the line background color

As you can see, I am still referring to the line number element (for a normal line of code that has the mouse over it).

**Comment by ajtruckle** [comment] 2020-04-28 11:14
What I need to do is find out how to set the background here:

```
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::before{
	padding: 1px 5px 1px 14px;
	font-size: 1.3em;
	color: black;
	background-color: whitesmoke;
	border-right:thin black solid;
}
```

To `inherit` when the normal row is hovered.

**Comment by AndiDittrich** [comment] 2020-04-28 11:15
did you tried to add an `!important` directive ?

**Comment by ajtruckle** [comment] 2020-04-28 11:20
Got it! As you said `:` verses `::`:

```
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div::before{
	padding: 1px 5px 1px 14px;
	font-size: 1.3em;
	color: black;
	background-color: whitesmoke;
	border-right:thin black solid;
}
.enlighter-t-trucklesoft.enlighter-linenumbers div.enlighter>div:hover::before{
	background-color: #53616f;
}
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special::before{
	background-color: #2F4F4F;
}
.enlighter-t-trucklesoft div.enlighter>div.enlighter-special:hover::before{
	background-color: #53616f;
}
```

**Comment by AndiDittrich** [comment] 2020-04-28 11:21
great!

btw. the basic css tutorials of w3schools or mdn are very comprehensive

**Closed by AndiDittrich** 2020-04-28 11:21 UTC
